using System.Globalization;
using System.Text;

namespace GameStatsGen;

public static class CodeGenerator
{
    public static string Render(Formulas f, string captureId)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// GENERATED FILE — do not hand-edit. Regenerate via:");
        sb.AppendLine($"//   dotnet run --project tools/GameStatsGen -- {captureId}");
        sb.AppendLine($"// Source: game-data/{captureId}/perf_A_{captureId}.csv + run_manifest.json");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Portfolio.Components;");
        sb.AppendLine();
        sb.AppendLine("namespace Portfolio.Pages;");
        sb.AppendLine();
        sb.AppendLine("public partial class Game");
        sb.AppendLine("{");

        sb.AppendLine("    // §1 — What is this?");
        Const(sb, "TotalHexTiles", f.TotalHexTiles());
        Const(sb, "PctFramesBelow30Overview", f.PctFramesBelow30Overview());
        Const(sb, "AvgFpsOverview", f.AvgFpsOverview());
        Const(sb, "TimeToFirstHex", f.TimeToFirstHex());
        Const(sb, "TreeCountWorld", f.TreeCountWorld());
        sb.AppendLine();
        DoubleArray(sb, "RunTimelineElapsedS", f.RunTimelineElapsedS());
        DoubleArray(sb, "RunTimelineFps", f.RunTimelineFps());
        PhasesArray(sb, "RunTimelinePhases", f.TimeToFirstHexValue(), f.TBuild);
        sb.AppendLine();

        sb.AppendLine("    // §2 — Building the world");
        Const(sb, "BuildTime", f.BuildTime());
        Const(sb, "PctFramesBelow30Build", f.PctFramesBelow30Build());
        sb.AppendLine();
        DoubleArray(sb, "HexesFinishedOverTime", f.HexesFinishedOverTime());
        DoubleArray(sb, "FpsOverTimeBuild", f.FpsOverTimeBuild());
        sb.AppendLine();
        Const(sb, "AvgRamPctBudget", f.AvgRamPctBudget());
        Const(sb, "MaxRamPctBudget", f.MaxRamPctBudget());
        sb.AppendLine();
        DoubleArray(sb, "RamPctOverTime", f.RamPctOverTime());
        sb.AppendLine();

        sb.AppendLine("    // Fixed presentation config — not derived from capture data.");
        sb.AppendLine("    static readonly LineChart.Threshold[] FpsThresholds =");
        sb.AppendLine("    [");
        sb.AppendLine("        new(30, \"30 fps\"),");
        sb.AppendLine("        new(60, \"60 fps\"),");
        sb.AppendLine("    ];");
        sb.AppendLine();
        sb.AppendLine("    static readonly LineChart.Marker[] BuildCompleteMarker =");
        sb.AppendLine("    [");
        sb.AppendLine($"        new({f.TBuild.ToString("0.###", CultureInfo.InvariantCulture)}, \"world complete\"),");
        sb.AppendLine("    ];");
        sb.AppendLine();

        sb.AppendLine("    // §3 — Once it is built");
        Const(sb, "MaxGpuPctBudget", f.MaxGpuPctBudget());
        Const(sb, "AvgGpuPctBudget", f.AvgGpuPctBudget());
        Const(sb, "DrawDistanceHexes", f.DrawDistanceHexes());
        Const(sb, "BiggestTrianglePctOfScreen", f.BiggestTrianglePctOfScreen());
        Const(sb, "ShadowsOnScreen", f.ShadowsOnScreen());
        Const(sb, "AvgFpsBuilt", f.AvgFpsBuilt());
        sb.AppendLine();
        DoubleArray(sb, "FpsOverTimeBuilt", f.FpsOverTimeBuilt());
        DoubleArray(sb, "GpuOverTime", f.GpuOverTime());

        sb.AppendLine("}");

        return sb.ToString();
    }

    static void Const(StringBuilder sb, string name, string value) =>
        sb.AppendLine($"    const string {name} = \"{value}\";");

    static void DoubleArray(StringBuilder sb, string name, double[] values)
    {
        var items = string.Join(", ", values.Select(v => v.ToString("0.###", CultureInfo.InvariantCulture)));
        sb.AppendLine($"    static readonly double[] {name} =");
        sb.AppendLine($"    [ {items} ];");
    }

    static void PhasesArray(StringBuilder sb, string name, double timeToFirstHex, double tBuild)
    {
        var sceneLoad = timeToFirstHex.ToString("0.0", CultureInfo.InvariantCulture);
        var worldFillsInLength = (tBuild - timeToFirstHex).ToString("0.0", CultureInfo.InvariantCulture);
        var freeFlightStart = tBuild.ToString("0.0", CultureInfo.InvariantCulture);
        var freeFlightLength = (60.0 - tBuild).ToString("0.0", CultureInfo.InvariantCulture);

        sb.AppendLine($"    static readonly RunTimeline.Phase[] {name} =");
        sb.AppendLine("    [");
        sb.AppendLine($"        new(\"scene load\", 0, {sceneLoad}),");
        sb.AppendLine($"        new(\"world fills in\", {sceneLoad}, {worldFillsInLength}, Highlight: true),");
        sb.AppendLine($"        new(\"free flight\", {freeFlightStart}, {freeFlightLength}),");
        sb.AppendLine("    ];");
    }
}
